//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.4
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 91121edd-87b6-4f13-9ed6-7c5515e54930 aws-my-sample-app-android-v0.4";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:8f237859-4920-41d6-87f3-87d153886389";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "compostthemostappfor-contentdelivery-mobilehub-2095335410";
    public static final String AMAZON_CLOUD_FRONT_DISTRIBUTION_DOMAIN =
        "dls5u9i1fxamm.cloudfront.net";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "compostthemostappfor-userfiles-mobilehub-2095335410";
}
